<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="Models\Collimator\**" />
    <Compile Remove="Models\Collimator\**" />
    <EmbeddedResource Remove="Models\Collimator\**" />
    <None Remove="Models\Collimator\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Level\LevelDataPageView.axaml.cs">
      <DependentUpon>LevelDataPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Global\SettingsPageView.axaml.cs">
      <DependentUpon>SettingsPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Global\MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Global\HomePageView.axaml.cs">
      <DependentUpon>HomePageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Global\GraphicPageView.axaml.cs">
      <DependentUpon>GraphicPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Global\ExitPageView.axaml.cs">
      <DependentUpon>ExitPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Collimator\CollimatorParamsPageView.axaml.cs">
      <DependentUpon>CollimatorParamsPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Collimator\CollimatorDataPageView.axaml.cs">
      <DependentUpon>LevelDataPageView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="OxyPlot.Avalonia" Version="2.1.0" />
  </ItemGroup>
</Project>
